### ISSUE TITLE
Trivial [bug] died without empty the health bar

### ISSUE THREAD

**Issue by littletoe** [bjmendez/Pesadilla#103]
This is a snapshot of this game after the character died.

![image](https://user-images.githubusercontent.com/14008278/38772563-8f6d69d6-4007-11e8-9de3-00b16d776715.png)

You can see that the health bar is almost full. How can it be cleared by one attack?

**Comment by bjmendez** [comment]
Ahh I see sorry! We will work right on it.

**Comment by bjmendez** [comment]
Thank you for the input Brian!

**Comment by bjmendez** [comment]
@jnboyd

**Comment by bjmendez** [comment]
resolved
