### ISSUE TITLE
[trivial bug] The character seized up by enemy

### ISSUE THREAD

**Issue by ziangzha** [bjmendez/Pesadilla#109]
After the enemy came close to me, the character seized up by the enemy and the wall. Can't moving anymore.

![qq 20180420042913](https://user-images.githubusercontent.com/36140953/39016850-3b6aaa14-4454-11e8-9c48-20b15667efc4.png)

**Comment by bjmendez** [comment]
Thank you this something we are looking at

**Comment by bjmendez** [comment]
resolved
