### ISSUE TITLE
MINOR BUG: Enemies go flying when you walk into them up or down

### ISSUE THREAD

**Issue by crw24** [bjmendez/Pesadilla#66]
When you bump into an enemy sprite and are moving up (w) or down (s) the enemy goes flying back across the map, making the player have to chase them down to kill them, or allows the player to just bump all enemies out of the way to pass levels.

When you bump into the enemy going left (a) or right (d), the enemies are pushed, but are pushed with the player.

**Comment by bjmendez** [comment]
Gonna go ahead and call this one a feature, not a bug. Haha just kidding! Thanks for letting us know and we will get right on that.

**Comment by crw24** [comment]
Really appreciate the prompt response! I really enjoyed this project, very nice work
